### PR TITLE
add update representation returned by map_final to munge in endpoint

### PR DESCRIPTION
**Pull request by kra**
untested

I didn't want to add an new attr and keep the old because the contents of channel have changed with implementation over the years and we need to use regexps to read them anyway.

https://github.com/futel/usage/issues/69

### CODE REVIEW

**Comment by kra** [comment]
how to verify? Watch existing SNS as it goes by and verify that the endpoint attr always holds a correct value for channel

**Comment by breedx2** [comment]
> I didn't want to add an new attr and keep the old because the contents of channel have changed with implementation over the years 

I know that `channel` is a viper pit, but wouldn't it be a bit more conservative and safer to emit both for a little while, at least until we can verify downstream that the UI stuff has all it needs? In other words, if `endpoint` is our future, let's not just shoehorn `endpoint` into `channel`, but instead emit `endpoint` and migrate downstream to use that completely before removing (or in this PR overriding) `channel`. 

> and we need to use regexps to read them anyway.

Don't hate.

**Comment by kra** [comment]
Updated to keep channel and add endpoint.

**Comment by kra** [comment]
SNS looks good.

```
from collections import defaultdict
out = defaultdict(set)
import json
with open('reader.out') as f:
    for line in f.readlines():
        j = json.loads(line)
        out[j['event'].get('Channel')].add(j['event'].get('endpoint'))

for e in out.values():
    if len(e) > 1:
        print(len(e))

print(out)
```

**Comment by kra** [comment]
> Don't hate.

I ONLY HATE THE EVIL THIS WORLD HAS SEEN FROM MY OWN HAND

**Pull request merged**
